language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run prod
deploy:
  provider: pages
  cleanup: true
  github_token: "528e10e5431ef08161962ae5c38a1eca8abfc255"
  local_dir: public
  on:
    branch: master