language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run prod
deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master